{% set python_min = "3.10" %}
{% set name = "txl-terminal" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_terminal-{{ version }}.tar.gz
  sha256: 316d4522c2ffc18561c56703be259740380a0db4abdb942202d51bf1ac7c2a3d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2
    - pyte >=0.8.1

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_terminal

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/terminal
  summary: TXL plugin for a terminal widget
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/terminal
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
