{% set python_min = "3.10" %}
{% set name = "txl-terminal" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_terminal-{{ version }}.tar.gz
  sha256: 3da66ddc5eef9ca8ff6ae6e14079702770b708a68bb96ca8a8637c9f1ab37a70

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - pyte >=0.8.1

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_terminal

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/terminal
  summary: TXL plugin for a terminal widget
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/terminal
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
