{% set name = "txl-terminal" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_terminal-{{ version }}.tar.gz
  sha256: ce1d21d3143e0ee94894f92b49d84d11e336c96cf26462ed554fa36bcce65544

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - pyte >=0.8.1

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_terminal

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/terminal
  summary: TXL plugin for a terminal widget
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/terminal
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
